"""独立命令行工具：从 TSV/JSON 弹幕生成 ASS 滚动弹幕文件。"""

import argparse
import datetime
import json
import math
import os
import sys


def parse_timestamp(timestamp_str):
    """
    灵活地将带有或不带毫秒的时间戳字符串转换为 datetime 对象。

    Args:
        timestamp_str (str): 要解析的时间戳字符串。

    Returns:
        datetime.datetime: 解析后的 datetime 对象。
        None: 如果无法解析，则返回 None。
    """
    # 尝试解析带毫秒的格式
    try:
        # %Y-%m-%d %H:%M:%S,%f 中的 %f 代表微秒
        # Python 的 datetime.strptime() 使用 %f 来处理毫秒和微秒，
        # 即使字符串只有毫秒，它也能正确解析。
        return datetime.datetime.strptime(
            timestamp_str, "%Y-%m-%d %H:%M:%S,%f"
        )
    except ValueError:
        # 如果失败，尝试解析不带毫秒的格式
        return datetime.datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S")


def format_timedelta_to_ass(td):
    """
    Formats a timedelta object to ASS time string (H:MM:SS.cc).
    将 timedelta 对象格式化为 ASS 时间字符串 (H:MM:SS.cc)。
    """
    total_seconds = int(td.total_seconds())
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    # ASS uses centiseconds (1/100 of a second)
    centiseconds = int(td.microseconds / 10000)
    return f"{hours}:{minutes:02}:{seconds:02}.{centiseconds:02}"


def _resolve_video_dimensions(video_file_path, video_width, video_height):
    """有 video_file_path 时从视频读取分辨率，失败则回退到给定值。

    cv2 是可选依赖，仅在此处按需导入；未安装时给出警告并回退，
    不影响其余功能。
    """
    if not video_file_path:
        return video_width, video_height
    try:
        import cv2

        cap = cv2.VideoCapture(video_file_path)
        if not cap.isOpened():
            raise IOError(f"无法打开视频文件: {video_file_path}")
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()
        print(
            f"从视频文件 '{video_file_path}' 获取到视频尺寸："
            f"宽度={width}, 高度={height}"
        )
        return width, height
    except Exception as e:
        print(
            f"警告: 无法从视频文件 '{video_file_path}' 获取尺寸。"
            f"将使用默认或指定参数值。错误: {e}"
        )
        return video_width, video_height


def _estimate_text_width(speaker, content, font_size):
    """估算 "[发言人]内容" 的显示宽度。

    含 CJK 字符时按 1.0 倍字号估算，否则按 0.6 倍。
    """
    full_text_for_width_estimate = f"[{speaker}]{content}"
    estimated_char_width_ratio = 0.6
    if any(
        "\u4e00" <= char <= "\u9fff" for char in full_text_for_width_estimate
    ):
        estimated_char_width_ratio = 1.0
    return len(full_text_for_width_estimate) * (
        font_size * estimated_char_width_ratio
    )


def _build_header(video_width, video_height, font_size):
    """生成 ASS 文件头（[Script Info]/[V4+ Styles]/[Events]）。

    返回值不含结尾换行。
    """
    style_format = (
        "Format: Name, Fontname, Fontsize, PrimaryColour, "
        "SecondaryColour, OutlineColour, BackColour, Bold, "
        "Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, "
        "Angle, BorderStyle, Outline, Shadow, Alignment, "
        "MarginL, MarginR, MarginV, Encoding"
    )
    style_line = (
        f"Style: DanmakuStyle,Arial,{font_size},"
        "&H00FFFFFF,&H000000FF,&H00000000,&H00000000,"
        "0,0,0,0,100,100,0,0,1,2,0,7,20,20,20,1"
    )
    event_format = (
        "Format: Layer, Start, End, Style, Name, MarginL, "
        "MarginR, MarginV, Effect, Text"
    )
    return (
        "[Script Info]\n"
        "; Script generated by a Python tool\n"
        "Title: Generated Scrolling Danmaku (TSV/JSON Input)\n"
        "ScriptType: v4.00+\n"
        "Collisions: Normal\n"
        f"PlayResX: {video_width}\n"
        f"PlayResY: {video_height}\n"
        "Timer: 100.0000\n"
        "\n"
        "[V4+ Styles]\n"
        f"{style_format}\n"
        f"{style_line}\n"
        "\n"
        "[Events]\n"
        f"{event_format}"
    )


def _parse_json_records(file_content, input_filepath):
    """解析 JSON 弹幕为 (datetime, speaker, content) 列表。

    出错时打印原因并返回 None（由调用方决定是否继续）。
    """
    items = []
    try:
        json_data = json.loads(file_content)
        if not isinstance(json_data, list):
            raise ValueError("JSON input must be a list of danmaku objects.")
        for line_num, item in enumerate(json_data, 1):
            if not all(k in item for k in ["timestamp", "speaker", "content"]):
                print(
                    f"警告: JSON 对象 {line_num} 缺少必要的键 "
                    "(timestamp, speaker, content)。跳过。"
                )
                continue
            datetime_str = item["timestamp"]
            speaker = item["speaker"]
            content = item["content"]
            current_datetime = parse_timestamp(datetime_str)
            items.append((current_datetime, speaker, content))
    except json.JSONDecodeError as e:
        print(
            f"错误: 无法解析 JSON 文件 '{input_filepath}'。"
            f"请检查 JSON 格式。错误: {e}"
        )
        return None
    except ValueError as e:  # Catch datetime parsing errors here
        print(f"JSON 数据中日期时间格式错误: {e}")
        return None
    except Exception as e:
        print(f"处理 JSON 数据时发生未知错误: {e}")
        return None
    return items


def _parse_tsv_records(file_content):
    """解析 TSV 弹幕为 (datetime, speaker, content) 列表。

    无法解析的行打印告警后跳过。
    """
    items = []
    for line_num, line in enumerate(file_content.splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            parts = line.split("\t", 2)
            if len(parts) != 3:
                raise ValueError("Incorrect number of columns")
            datetime_str, speaker, content = parts
            current_datetime = datetime.datetime.strptime(
                datetime_str, "%Y-%m-%d %H:%M:%S"
            )
            items.append((current_datetime, speaker, content))
        except ValueError as e:
            print(
                f"警告: 跳过无效行 {line_num}: '{line}'。"
                "格式应为 'YYYY-MM-DD HH:MM:SS\\t发言人\\t弹幕内容'。"
                f"错误: {e}"
            )
            continue
        except Exception as e:
            print(f"处理 TSV 文件行 {line_num} 时发生未知错误: {e}")
            continue
    return items


def _build_records(items, reference_datetime, font_size):
    """把解析结果转成带 timestamp_ms/text_width 的记录并排序。"""
    if reference_datetime is None:
        # 未指定视频起始时间时，以第一条弹幕时间为基准
        reference_datetime = items[0][0]
    records = []
    for current_datetime, speaker, content in items:
        timestamp_ms = int(
            (current_datetime - reference_datetime).total_seconds() * 1000
        )
        records.append(
            {
                "timestamp_ms": timestamp_ms,
                "speaker": speaker,
                "content": content,
                "text_width": _estimate_text_width(
                    speaker, content, font_size
                ),
            }
        )
    records.sort(key=lambda x: x["timestamp_ms"])
    return records


def _load_danmaku_records(input_filepath, video_start_datetime_str, font_size):
    """读取并解析弹幕文件，返回按时间排序的记录列表。

    任何一步失败都打印原因并返回 None。
    """
    reference_datetime = None
    if video_start_datetime_str:
        try:
            reference_datetime = parse_timestamp(video_start_datetime_str)
        except ValueError:
            print(
                f"错误: 无效的 video_start_datetime_str 格式 "
                f"'{video_start_datetime_str}'。"
                "应为 'YYYY-MM-DD HH:MM:SS'。"
            )
            return None
    try:
        with open(input_filepath, "r", encoding="utf-8") as f:
            file_content = f.read()
    except FileNotFoundError:
        print(f"错误: 找不到输入文件 '{input_filepath}'。")
        return None
    except Exception as e:
        print(f"读取输入文件 '{input_filepath}' 时发生未知错误: {e}")
        return None

    file_extension = os.path.splitext(input_filepath)[1].lower()
    if file_extension == ".json":
        items = _parse_json_records(file_content, input_filepath)
    else:
        items = _parse_tsv_records(file_content)
    if items is None:
        return None
    if not items:
        print("没有可用的弹幕数据进行处理。请检查输入文件内容。")
        return None
    return _build_records(items, reference_datetime, font_size)


def _layout_danmaku(
    records,
    video_width,
    num_channels,
    line_height,
    scroll_speed_pixels_per_second,
    buffer_pixels_after_tail_enters,
):
    """为每条弹幕分配轨道并生成 Dialogue 行。

    轨道在弹幕尾部完全展现后加上缓冲距离即可被视为空闲；
    无空闲轨道时推迟到最早释放的轨道。
    """
    # Initial offset from right edge of screen for danmaku to start
    padding_right_of_screen = 50
    # Offset from left edge of screen for danmaku to fully exit
    padding_left_of_screen = 50
    # 定义颜色，使用 ASS BGR 十六进制格式：&HBBGGRR&
    # 发言人浅蓝色，弹幕内容白色
    speaker_color_ass = "&HFFC0C0&"  # Light Blue
    content_color_ass = "&H00FFFFFF&"  # White (same as PrimaryColour)

    channel_free_time = [datetime.timedelta(0)] * num_channels
    dialogue_lines = []
    for danmaku in records:
        desired_start_time_td = datetime.timedelta(
            milliseconds=danmaku["timestamp_ms"]
        )
        # 滚动起始/结束X坐标（弹幕文本左边缘的移动范围）
        start_x = video_width + padding_right_of_screen
        end_x = -danmaku["text_width"] - padding_left_of_screen
        # 弹幕左边缘滚动的总距离
        total_scroll_distance = start_x - end_x
        # 根据速度和总距离计算当前弹幕的实际滚动时长
        scroll_duration_current_danmaku = datetime.timedelta(
            seconds=total_scroll_distance / scroll_speed_pixels_per_second
        )

        # 寻找空闲通道；没有则记录最早释放的通道
        assigned_channel = -1
        earliest_free_time = datetime.timedelta.max
        assigned_channel_if_wait = 0
        for i in range(num_channels):
            if channel_free_time[i] <= desired_start_time_td:
                assigned_channel = i
                break
            elif channel_free_time[i] < earliest_free_time:
                earliest_free_time = channel_free_time[i]
                assigned_channel_if_wait = i
        actual_danmaku_start_time_td = desired_start_time_td
        if assigned_channel == -1:
            assigned_channel = assigned_channel_if_wait
            actual_danmaku_start_time_td = earliest_free_time

        danmaku_full_exit_time_td = (
            actual_danmaku_start_time_td + scroll_duration_current_danmaku
        )
        # 弹幕尾部完全进入屏幕所移动的距离
        distance_for_tail_to_enter_screen = start_x - (
            video_width - danmaku["text_width"]
        )
        time_for_tail_to_enter_screen_relative_to_start = datetime.timedelta(
            seconds=distance_for_tail_to_enter_screen
            / scroll_speed_pixels_per_second
        )
        buffer_time_td = datetime.timedelta(
            seconds=buffer_pixels_after_tail_enters
            / scroll_speed_pixels_per_second
        )
        # 释放时间 = 尾部进屏时间 + 缓冲时间
        channel_release_time_td = (
            actual_danmaku_start_time_td
            + time_for_tail_to_enter_screen_relative_to_start
            + buffer_time_td
        )
        # 释放时间不超过弹幕完全滚出屏幕的时间
        channel_release_time_td = min(
            channel_release_time_td, danmaku_full_exit_time_td
        )
        channel_free_time[assigned_channel] = channel_release_time_td

        # Alignment 7 表示垂直居中，y_pos 是文本的垂直中心线
        y_pos = assigned_channel * line_height + (line_height / 2)

        # {\c&HBBGGRR&} 设置颜色
        formatted_text = (
            f"{{\\c{speaker_color_ass}}}[{danmaku['speaker']}]"
            f"{{\\c{content_color_ass}}}{danmaku['content']}"
        )
        # 使用 \move 标签实现从右向左滚动
        start_str = format_timedelta_to_ass(actual_danmaku_start_time_td)
        end_str = format_timedelta_to_ass(danmaku_full_exit_time_td)
        ass_line = (
            f"Dialogue: 0,{start_str},{end_str},"
            f"DanmakuStyle,,0,0,0,,"
            f"{{\\move({start_x},{y_pos},{end_x},{y_pos})}}"
            f"{formatted_text}"
        )
        dialogue_lines.append(ass_line)
    return dialogue_lines


def generate_ass_scrolling_danmaku(
    input_filepath,
    output_filepath,
    video_width_param=1280,
    video_height_param=720,
    font_size=48,
    scroll_speed_pixels_per_second=100,
    buffer_pixels_after_tail_enters=50,
    video_start_datetime_str=None,
    video_file_path=None,
):
    """
    根据原始弹幕文本和时间戳生成 ASS 滚动弹幕文件，并尝试避免垂直重叠。

    原始弹幕数据格式：
    TSV: 日期时间字符串\\t弹幕发言人\\t弹幕内容
    JSON: [{ "timestamp": "YYYY-MM-DD HH:MM:SS",
             "speaker": "发言人", "content": "弹幕内容" }, ...]
    日期时间格式示例：2025-07-02 14:11:19
    显示格式：浅蓝色字体方括号包围的发言人，白色弹幕内容。

    Args:
        input_filepath: 弹幕文件路径，支持 TSV 或 JSON 格式。
        output_filepath: 生成的 ASS 文件的输出路径。
        video_width_param: 视频宽度（像素），无 video_file_path 时生效。
        video_height_param: 视频高度（像素），无 video_file_path 时生效。
        font_size: 弹幕的字体大小。
        scroll_speed_pixels_per_second: 弹幕每秒滚动的像素数。
        buffer_pixels_after_tail_enters: 尾部进屏后的像素缓冲距离。
        video_start_datetime_str: 视频起始时间，格式
            'YYYY-MM-DD HH:MM:SS'；未提供时使用第一条弹幕时间。
        video_file_path: 视频文件路径；提供时从该文件读取分辨率并
            覆盖 video_width_param 和 video_height_param。
    """
    video_width, video_height = _resolve_video_dimensions(
        video_file_path, video_width_param, video_height_param
    )

    # 根据字体大小估算的行高（Alignment 7 行间留 10 像素缓冲）
    line_height = font_size + 10
    # 计算可用的垂直通道数量
    num_channels = math.floor(video_height / line_height)
    if num_channels <= 0:
        print(
            "错误: 视频高度太小，无法容纳任何弹幕轨道。"
            "请检查 video_height 或 font_size。"
        )
        return

    danmaku_records = _load_danmaku_records(
        input_filepath, video_start_datetime_str, font_size
    )
    if danmaku_records is None:
        return

    ass_header = _build_header(video_width, video_height, font_size)
    dialogue_lines = _layout_danmaku(
        danmaku_records,
        video_width,
        num_channels,
        line_height,
        scroll_speed_pixels_per_second,
        buffer_pixels_after_tail_enters,
    )

    with open(output_filepath, "w", encoding="utf-8") as f:
        f.write(ass_header + "\n")
        for line in dialogue_lines:
            f.write(line + "\n")

    print(f"成功生成 ASS 文件：'{output_filepath}'")
    print(
        f"请确保视频的尺寸与脚本中设置的 "
        f"video_width={video_width}, video_height={video_height} "
        "一致，以获得最佳效果。"
    )
    print(f"总共分配了 {num_channels} 个弹幕轨道。")
    print(
        f"每行弹幕估算高度为 {line_height} 像素，"
        f"行尾缓冲为 {buffer_pixels_after_tail_enters} 像素。"
    )


# --- 使用示例 ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Generate ASS scrolling danmaku from TSV or JSON input. "
            "Automatically detects input file format based on "
            "extension (.tsv or .json)."
        ),
        # Preserve newlines in help text
        formatter_class=argparse.RawTextHelpFormatter,
    )

    parser.add_argument(
        "input_filepath",
        type=str,
        help=(
            "Path to the input TSV or JSON file "
            "(e.g., input.tsv or input.json)"
        ),
    )
    parser.add_argument(
        "output_filepath",
        type=str,
        help="Path to the output ASS file (e.g., output.ass)",
    )
    parser.add_argument(
        "--video_width",
        type=int,
        default=1280,
        help=(
            "Width of the video in pixels. Used if --video_file is "
            "not provided or fails. (default: 1280)"
        ),
    )
    parser.add_argument(
        "--video_height",
        type=int,
        default=720,
        help=(
            "Height of the video in pixels. Used if --video_file is "
            "not provided or fails. (default: 720)"
        ),
    )
    parser.add_argument(
        "--font_size",
        type=int,
        default=48,
        help="Font size of the danmaku (default: 48)",
    )
    parser.add_argument(
        "--scroll_speed",
        type=int,
        default=100,
        help=("Danmaku scroll speed in pixels per second (default: 100)"),
    )
    parser.add_argument(
        "--buffer_pixels",
        type=int,
        default=50,
        help=("Buffer pixels after danmaku tail enters screen (default: 50)"),
    )
    parser.add_argument(
        "--video_start_time",
        type=str,
        default=None,
        help=(
            "Video's start datetime in 'YYYY-MM-DD HH:MM:SS' format. "
            "If not provided, the first danmaku's time will be used "
            "as video start."
        ),
    )
    parser.add_argument(
        "--video_file",
        type=str,
        default=None,
        help=(
            "Path to the video file (e.g., video.mp4). If provided, "
            "script will try to get video width and height from it, "
            "overriding --video_width and --video_height."
        ),
    )

    # If no arguments are provided, print help message and exit
    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    args = parser.parse_args()

    generate_ass_scrolling_danmaku(
        input_filepath=args.input_filepath,
        output_filepath=args.output_filepath,
        video_width_param=args.video_width,
        video_height_param=args.video_height,
        font_size=args.font_size,
        scroll_speed_pixels_per_second=args.scroll_speed,
        buffer_pixels_after_tail_enters=args.buffer_pixels,
        video_start_datetime_str=args.video_start_time,
        video_file_path=args.video_file,
    )

    # Example input.tsv content:
    # 2025-07-02 14:11:19	用户A	这是一条测试弹幕！
    # 2025-07-02 14:11:20	发言人B	紧随其后，但会在不同轨道。
    # 2025-07-02 14:11:21	管理员	第三条，内容可以长一些。

    # Example input.json content:
    # [
    #     {
    #         "timestamp": "2025-07-02 14:11:19",
    #         "speaker": "用户A",
    #         "content": "这是一条测试弹幕！"
    #     },
    #     {
    #         "timestamp": "2025-07-02 14:11:20",
    #         "speaker": "发言人B",
    #         "content": "紧随其后，但会在不同轨道。"
    #     },
    #     {
    #         "timestamp": "2025-07-02 14:11:21",
    #         "speaker": "管理员",
    #         "content": "第三条，内容可以长一些。"
    #     }
    # ]
